;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        dabbrev-expand
        end-of-buffer
        end-of-visual-line
        indent-for-tab-command
        kill-region
        kill-visual-line
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        drag-stuff-left
        drag-stuff-right
        ido-switch-buffer
        smex
        ))
